name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.2.4+21
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  # bip32: ^1.0.5
  bip32:
    git:
      url: git://github.com/dart-bitcoin/bip32-dart.git
      ref: "1e15731"


  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.1
  # resource: ^2.1.7 # not use
  # web3dart: ^1.2.3
  web3dart:
      git:
        url: git://github.com/better-dart/web3dart.git
        ref: migrate-to-v2-null-safety      # commit id
  graphql: ^5.0.0-nullsafety.3
  decimal: ^1.0.0+1
