name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.2.4+23
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  bip32: ^1.0.5
  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.3
  resource: ^2.1.7


#  web3dart: ^1.2.3
#  web3dart:
#    path: /Users/henry/Documents/iSpace/better-dart/web3dart
  web3dart:
    git:
      url: https://github.com/better-dart/web3dart.git
      ref: v2-null-safety # branch

  # color logger:
  logger: ^1.0.0

  graphql: ^5.0.0-nullsafety.5
  decimal: ^1.1.0
